services:
    _defaults:
        public: true

    # テスト時はCsrfTokenManagerはMockを利用する
    security.csrf.token_manager:
        class: Eccube\Tests\Mock\CsrfTokenManagerMock
        public: true
    # テスト時はTransactionListenerを無効にする
    Eccube\EventListener\TransactionListener:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - false
    # セッションの保存先をvar/sessions/testに変更する
    session.storage.mock_file:
        class: 'Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorage'
        arguments:
            - '%session.save_path%'
            - 'MOCKSESSID'
            - '@session.storage.metadata_bag'

    Eccube\Repository\:
        resource: '../../../src/Eccube/Repository'
        autowire: true
        autoconfigure: true
        public: true

    Eccube\Service\PurchaseFlow\Processor\:
        resource: '../../../src/Eccube/Service/PurchaseFlow/Processor'
        autowire: true
        autoconfigure: true
        public: true

    Eccube\Service\OrderHelper:
        autowire: true
        public: true
    Eccube\Service\MailService:
        autowire: true
        public: true
    Eccube\Service\PluginService:
        autowire: true
        public: true
    Eccube\Service\EntityProxyService:
        autowire: true
        public: true
    Eccube\Service\CsvExportService:
        autowire: true
        public: true
    Eccube\Service\CartService:
        autowire: true
        public: true
    Eccube\Service\TaxRuleService:
        autowire: true
        public: true
    Eccube\Service\SystemService:
        autowire: true
        public: true
    Eccube\Command\DeleteCartsCommand:
        autowire: true
        public: true
    Eccube\Security\Core\Encoder\PasswordEncoder:
        autowire: true
        public: true
    Eccube\Security\Core\Encoder:
        autowire: true
        public: true

    eccube.util.cache_util: '@Eccube\Util\CacheUtil'
    eccube.service.order_state_machine: '@Eccube\Service\OrderStateMachine'
    test.eccube.purchase.flow.cart: '@eccube.purchase.flow.cart'
    test.eccube.purchase.flow.order: '@eccube.purchase.flow.order'
    test.eccube.purchase.flow.shopping: '@eccube.purchase.flow.shopping'

