# for travis-ci
# see also. https://travis-ci.org
git:
  submodules: false

sudo: false

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $(gem environment gemdir)

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  matrix:
    - DB=mysql ECCUBE_DB_USERNAME=root ECCUBE_DB_PASSWORD=
    - DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password
    - DB=sqlite
    # カバレッジレポート用
    - DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password COVERAGE=true

matrix:
  fast_finish: true
  exclude:
    # php7.1以外のカバレッジレポート用matrixは除外
    - php: 5.6
      env: DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password COVERAGE=true
    - php: 7.0
      env: DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password COVERAGE=true
    - php: 7.2
      env: DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password COVERAGE=true
  allow_failures:
    # sqlite
    - env: DB=sqlite
    # カバレッジレポートはphp7.1のmatrixで実行
    - php: 7.1
      env: DB=pgsql ECCUBE_DB_USERNAME=postgres ECCUBE_DB_PASSWORD=password COVERAGE=true

install:
  # @see https://github.com/sj26/mailcatcher/issues/277
  - gem install mime-types --version "< 3"
  - gem install --conservative mailcatcher

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --dev --no-interaction -o
  - php ./eccube_install.php $DB none
  - mailcatcher

script:
  - if [ $COVERAGE ]  ; then phpdbg -qrr vendor/bin/simple-phpunit --coverage-clover=coverage.clover ; fi
  - if [ ! $COVERAGE ]; then vendor/bin/simple-phpunit; fi

after_script:
  - if [ $COVERAGE ]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [ $COVERAGE ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
  - if [ $COVERAGE ]; then php vendor/bin/coveralls -v -x coverage.clover ; fi
